server:
#  host: 192.168.1.4
  host: 172.20.10.2
  port: 8008
  static_dir: static
postgres:
  host: 192.168.88.132
  port: 5432
  user: postgres
  password: root
  database: qpr
#  database: recommend
redis:
  host: 192.168.88.132
  port: 6379
  password: root
  db: 0
jwt:
  secret: qpr